#!/usr/bin/env bash
# Install and configure nginx
# to return 'Hello World!' on a GET request
# to /

sudo apt-get -y update
sudo apt-get intall nginx -y

sudo ufw all 'Nginx HTTP'

mkdir -p /var/www/html
touch /var/www/html/index.html

echo "Hello World" > /var/www/html/index.html
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm intex.nginx-debian
html
}" > /etc/nginx/sites-available/default

sudo nginx -s reload
